### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by voitovdima** [voitovdima/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by mudro-online** [comment]
Не указывай только свою аську, кроме тебя и Васермана, нею уже не кто не пользуется

**Comment by voitovdima** [comment]
Ася вечная, как и почтовые голуби
